apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: three-per-min
config:
  minute: 1
  policy: local
plugin: rate-limiting


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: three-per-min,

spec:
  rules:
    - http:
        paths:
          - path: /v1/tasks/task
            pathType: Prefix
            backend:
              service:
                name: flaskproducer
                port:
                  number: 80
          - path: /v1/hello
            pathType: Prefix
            backend:
              service:
                name: hello
                port:
                  number: 80


